### ISSUE TITLE
merging loops logic

### ISSUE THREAD

**Issue by yklym** [Bodichelly/s_e_m#2]
https://github.com/Bodichelly/s_e_m/blob/1a964d8754a71c162997c074c0091ea59d13026e/lab1/main.py#LL35C1-L40C1

**Comment by Bodichelly** [comment]
It is necessary to keep loops separate. The first loop is for the main logic processing, while the second loop sets up the status. If the status setup occurs within the iterations of the main logic, it will impact the results.
